### PR TITLE
fix: don't set `LUA_INIT` if lux-lua not present

### LINKED ISSUE #755: `lx path`: don't set `LUA_INIT` if lux-lua isn't installed
Image

Image

### PR DESCRIPTION
**Pull request by mrcjkb**
Closes #755

### CODE REVIEW

File: lux-lib/src/path.rs [hunk 1]
```diff
@@ -63,28 +63,14 @@ impl Paths {
...
-            .map(PathBuf::from)
-            .unwrap_or_else(|| {
-                pkg_config::Config::new()
-                    .print_system_libs(false)
-                    .cargo_metadata(false)
-                    .env_metadata(false)
-                    .probe(&lib_name)
-                    .ok()
-                    .and_then(|library| library.link_paths.first().cloned())
-                    .unwrap_or_else(|| Config::get_default_data_path().unwrap())
```
Comment (mrcjkb) [inline lux-lib/src/path.rs:77]: @vhyrro I've removed the `.unwrap_or_else(|| Config::get_default_data_path().unwrap())` line, because we can't determine if lux-lua is available with it.
Do you know if this could break something?

Comment (vhyrro) [reply lux-lib/src/path.rs:77]: I can't see an immediate problem with that, so I'd say it's fine

**Review by vhyrro — DISMISSED** [review]
